# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'AdiscopeLuckyEvent', '5.2.3'
  pod 'AdiscopeMediaAdManager', '5.2.0'
  pod 'AdiscopeMediaAdMob', '5.2.0'
  pod 'AdiscopeMediaChartBoost', '5.2.0'
  pod 'AdiscopeMediaPangle', '5.2.0'
  pod 'AdiscopeMediaTnkPub', '5.2.0'
  pod 'AdiscopeMediaVungle', '5.2.0'
  pod 'AdiscopeMediaMax', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterAdManager', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterAdMob', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterAmazon', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterBidMachine', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterBigo', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterChartBoost', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterDTExchange', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterFan', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterInMobi', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterIronSource', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterLine', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterMobVista', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterMoloco', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterOgury', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterPangle', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterPubMatic', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterUnityAds', '5.2.0'
  pod 'AdiscopeMediaMaxAdapterVungle', '5.2.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
